### ISSUE TITLE
MailDev crashes when receiving message from exim SMTP client

### ISSUE THREAD

**Issue by jamesooo** [djfarrelly/MailDev#153]
Hello,
I'm getting the following error whenever i try to send a message from exim to my MailDev server:
```
TypeError: Cannot read property 'context' of undefined
at requestOCSP (_tls_wrap.js:130:10)
at _tls_wrap.js:180:5
at loadSNI (_tls_wrap.js:101:12)
at TLSSocket.oncertcb (_tls_wrap.js:177:3)
MailDev app running at 0.0.0.0:80
MailDev SMTP Server running at 0.0.0.0:25
_tls_wrap.js:130
 if (ctx.context)
 ^
```

is throws an error on the exim side showing:
```
[root@50c9bf486c6f html]# exim -v my@email.com
From: user@your.domain.example
To: postmaster@your.domain.example
Subject: Testing Exim

This is a test message.
LOG: MAIN
  <= root@ U=root P=local S=337
[root@50c9bf486c6f html]# delivering 1cR6qs-00002i-Ht
Connecting to 172.18.0.6 [172.18.0.6]:25 ... connected
  SMTP<< 220 55587a66bf85 ESMTP
  SMTP>> EHLO
  SMTP<< 250-OK: Nice to meet you mage_nginx.ppidevel_default
         250-PIPELINING
         250-8BITMIME
         250-SMTPUTF8
         250 STARTTLS
  SMTP>> STARTTLS
  SMTP<< 220 Ready to start TLS
LOG: MAIN
  TLS error on connection to 172.18.0.6 [172.18.0.6] (SSL_connect): error:00000000:lib(0):func(0):reason(0)
LOG: MAIN
  TLS session failure: delivering unencrypted to 172.18.0.6 [172.18.0.6] (not in hosts_require_tls)
Transport port=25 replaced by host-specific port=25
Connecting to 172.18.0.6 [172.18.0.6]:25 ... failed: Connection refused
LOG: MAIN
  172.18.0.6 [172.18.0.6] Connection refused
LOG: MAIN
  == my@email.com R=maildev T=remote_smtp defer (111): Connection refused
```
anyone have any idea what might be causing this?

**Comment by jamesooo** [comment]
looks like this is related to tls validation with MailDev. there seems to be something broken there. when i change my transport config to 
```
remote_smtp:
  driver = smtp
  hosts_avoid_tls = maildev
```
the issue goes away

**Comment by neeksor** [comment]
I believe it's related to this bug: https://github.com/nodejs/node/pull/10706

**Comment by jamesooo** [comment]
Cool that sounds right. Thanks for the response. I'll mark this as closed since it isn't a maildev bug
