### ISSUE TITLE
Maildev install error on Ubuntu Server 14.04.2

### ISSUE THREAD

**Issue by babeuloula** [djfarrelly/MailDev#79]
Hello, 

I've an error when I try to install Maildev on my local server with Ubuntu Server 14.04.2

```
npm http GET https://registry.npmjs.org/maildev
npm http 304 https://registry.npmjs.org/maildev
npm http GET https://registry.npmjs.org/mailcomposer
npm http GET https://registry.npmjs.org/open
npm http GET https://registry.npmjs.org/mailparser
npm http GET https://registry.npmjs.org/simplesmtp
npm http GET https://registry.npmjs.org/smtp-connection
npm http GET https://registry.npmjs.org/smtp-server
npm http GET https://registry.npmjs.org/socket.io
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/mailcomposer
npm http 304 https://registry.npmjs.org/open
npm http 304 https://registry.npmjs.org/mailparser
npm http 304 https://registry.npmjs.org/socket.io
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/express
npm http 304 https://registry.npmjs.org/smtp-connection
npm http 304 https://registry.npmjs.org/smtp-server
npm http 304 https://registry.npmjs.org/simplesmtp
npm WARN engine smtp-server@1.4.2: wanted: {"node":">=0.12"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET https://registry.npmjs.org/graceful-readlink
npm http GET https://registry.npmjs.org/he
npm http GET https://registry.npmjs.org/dkim-signer
npm http GET https://registry.npmjs.org/follow-redirects/0.0.3
npm http GET https://registry.npmjs.org/mimelib
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/socket.io-client/1.3.6
npm http GET https://registry.npmjs.org/socket.io-adapter/0.3.1
npm http GET https://registry.npmjs.org/has-binary-data/0.1.3
npm http GET https://registry.npmjs.org/debug/2.1.0
npm http GET https://registry.npmjs.org/engine.io/1.5.2
npm http GET https://registry.npmjs.org/socket.io-parser/2.2.4
npm http GET https://registry.npmjs.org/rai
npm http GET https://registry.npmjs.org/xoauth2
npm http 304 https://registry.npmjs.org/graceful-readlink
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/he
npm http 304 https://registry.npmjs.org/mimelib
npm http GET https://registry.npmjs.org/uue
npm http GET https://registry.npmjs.org/encoding
npm http GET https://registry.npmjs.org/mimelib
npm http 304 https://registry.npmjs.org/follow-redirects/0.0.3
npm http 304 https://registry.npmjs.org/has-binary-data/0.1.3
npm http 304 https://registry.npmjs.org/socket.io-adapter/0.3.1
npm http GET https://registry.npmjs.org/array-flatten/1.1.0
npm http GET https://registry.npmjs.org/content-type
npm http GET https://registry.npmjs.org/content-disposition/0.5.0
npm http GET https://registry.npmjs.org/cookie/0.1.3
npm http GET https://registry.npmjs.org/cookie-signature/1.0.6
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/escape-html/1.0.2
npm http GET https://registry.npmjs.org/depd
npm http GET https://registry.npmjs.org/etag
npm http GET https://registry.npmjs.org/finalhandler/0.4.0
npm http GET https://registry.npmjs.org/fresh/0.3.0
npm http GET https://registry.npmjs.org/merge-descriptors/1.0.0
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/on-finished
npm http GET https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/path-to-regexp/0.1.6
npm http GET https://registry.npmjs.org/qs/4.0.0
npm http GET https://registry.npmjs.org/proxy-addr
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/send/0.13.0
npm http GET https://registry.npmjs.org/serve-static
npm http GET https://registry.npmjs.org/type-is
npm http GET https://registry.npmjs.org/vary
npm http GET https://registry.npmjs.org/utils-merge/1.0.0
npm http GET https://registry.npmjs.org/accepts
npm http 304 https://registry.npmjs.org/socket.io-client/1.3.6
npm http 304 https://registry.npmjs.org/engine.io/1.5.2
npm http 304 https://registry.npmjs.org/dkim-signer
npm http 304 https://registry.npmjs.org/socket.io-parser/2.2.4
npm http 304 https://registry.npmjs.org/debug/2.1.0
npm http 304 https://registry.npmjs.org/xoauth2
npm http 304 https://registry.npmjs.org/encoding
npm http 304 https://registry.npmjs.org/mimelib
npm http 304 https://registry.npmjs.org/content-type
npm http 304 https://registry.npmjs.org/rai
npm http 304 https://registry.npmjs.org/cookie-signature/1.0.6
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/cookie/0.1.3
npm http 304 https://registry.npmjs.org/array-flatten/1.1.0
npm http 304 https://registry.npmjs.org/content-disposition/0.5.0
npm http 304 https://registry.npmjs.org/escape-html/1.0.2
npm http 304 https://registry.npmjs.org/depd
npm http 304 https://registry.npmjs.org/etag
npm http 304 https://registry.npmjs.org/fresh/0.3.0
npm http 304 https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/on-finished
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/object-keys/1.0.1
npm http GET https://registry.npmjs.org/debug/1.0.2
npm http GET https://registry.npmjs.org/socket.io-parser/2.2.2
npm http 304 https://registry.npmjs.org/uue
npm http 304 https://registry.npmjs.org/proxy-addr
npm http 304 https://registry.npmjs.org/merge-descriptors/1.0.0
npm http 304 https://registry.npmjs.org/range-parser
npm http 304 https://registry.npmjs.org/path-to-regexp/0.1.6
npm http 304 https://registry.npmjs.org/serve-static
npm http 304 https://registry.npmjs.org/type-is
npm http 304 https://registry.npmjs.org/vary
npm http 304 https://registry.npmjs.org/utils-merge/1.0.0
npm http 304 https://registry.npmjs.org/accepts
npm http 304 https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/send/0.13.0
npm http GET https://registry.npmjs.org/addressparser
npm http 304 https://registry.npmjs.org/object-keys/1.0.1
npm http 304 https://registry.npmjs.org/socket.io-parser/2.2.2
npm http 304 https://registry.npmjs.org/addressparser
npm http 304 https://registry.npmjs.org/debug/1.0.2
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/finalhandler/0.4.0
npm http GET https://registry.npmjs.org/iconv-lite
npm http 304 https://registry.npmjs.org/qs/4.0.0
npm http GET https://registry.npmjs.org/array.prototype.findindex
npm http GET https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/debug/1.0.3
npm http GET https://registry.npmjs.org/engine.io-parser/1.2.1
npm http GET https://registry.npmjs.org/ws/0.7.2
npm http 304 https://registry.npmjs.org/iconv-lite
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/debug/1.0.3
npm http 304 https://registry.npmjs.org/engine.io-parser/1.2.1
npm http 304 https://registry.npmjs.org/ws/0.7.2
npm http 304 https://registry.npmjs.org/array.prototype.findindex
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/debug/0.7.4
npm http GET https://registry.npmjs.org/json3/3.2.6
npm http GET https://registry.npmjs.org/component-emitter/1.1.2
npm http GET https://registry.npmjs.org/benchmark/1.0.0
npm http GET https://registry.npmjs.org/unpipe
npm http GET https://registry.npmjs.org/ee-first/1.1.1
npm http GET https://registry.npmjs.org/forwarded
npm http GET https://registry.npmjs.org/media-typer/0.3.0
npm http GET https://registry.npmjs.org/ipaddr.js/1.0.1
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/negotiator/0.5.3
npm http 304 https://registry.npmjs.org/json3/3.2.6
npm http 304 https://registry.npmjs.org/component-emitter/1.1.2
npm http GET https://registry.npmjs.org/statuses
npm http GET https://registry.npmjs.org/destroy/1.0.3
npm http GET https://registry.npmjs.org/http-errors
npm http GET https://registry.npmjs.org/mime/1.3.4
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/benchmark/1.0.0
npm http 304 https://registry.npmjs.org/unpipe
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/forwarded
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/debug/0.7.4
npm http 304 https://registry.npmjs.org/statuses
npm http 304 https://registry.npmjs.org/media-typer/0.3.0
npm http 304 https://registry.npmjs.org/ipaddr.js/1.0.1
npm http 304 https://registry.npmjs.org/http-errors
npm http 304 https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/destroy/1.0.3
npm http 304 https://registry.npmjs.org/mime/1.3.4
npm http GET https://registry.npmjs.org/has-binary/0.1.6
npm http GET https://registry.npmjs.org/object-component/0.0.3
npm http GET https://registry.npmjs.org/indexof/0.0.1
npm http GET https://registry.npmjs.org/parseuri/0.0.2
npm http GET https://registry.npmjs.org/to-array/0.1.3
npm http GET https://registry.npmjs.org/backo2/1.0.2
npm http GET https://registry.npmjs.org/engine.io-client/1.5.2
npm http GET https://registry.npmjs.org/component-bind/1.0.0
npm http 304 https://registry.npmjs.org/negotiator/0.5.3
npm http 304 https://registry.npmjs.org/parseuri/0.0.2
npm http GET https://registry.npmjs.org/after/0.8.1
npm http GET https://registry.npmjs.org/arraybuffer.slice/0.0.6
npm http GET https://registry.npmjs.org/base64-arraybuffer/0.1.2
npm http GET https://registry.npmjs.org/blob/0.0.2
npm http GET https://registry.npmjs.org/has-binary/0.1.5
npm http GET https://registry.npmjs.org/utf8/2.0.0
npm http 304 https://registry.npmjs.org/to-array/0.1.3
npm http 304 https://registry.npmjs.org/backo2/1.0.2
npm http 304 https://registry.npmjs.org/has-binary/0.1.6
npm http 304 https://registry.npmjs.org/object-component/0.0.3
npm http 304 https://registry.npmjs.org/indexof/0.0.1
npm http 304 https://registry.npmjs.org/engine.io-client/1.5.2
npm http 304 https://registry.npmjs.org/ee-first/1.1.1
npm http 304 https://registry.npmjs.org/component-bind/1.0.0
npm http 304 https://registry.npmjs.org/after/0.8.1
npm http 304 https://registry.npmjs.org/arraybuffer.slice/0.0.6
npm http 304 https://registry.npmjs.org/blob/0.0.2
npm http 304 https://registry.npmjs.org/has-binary/0.1.5
npm http 304 https://registry.npmjs.org/utf8/2.0.0
npm http 304 https://registry.npmjs.org/base64-arraybuffer/0.1.2
npm http GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/better-assert
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/better-assert
npm http GET https://registry.npmjs.org/bufferutil
npm http GET https://registry.npmjs.org/utf-8-validate
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/ultron
npm http 304 https://registry.npmjs.org/bufferutil
npm http GET https://registry.npmjs.org/callsite/1.0.0
npm http 304 https://registry.npmjs.org/utf-8-validate
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/ultron
npm http 304 https://registry.npmjs.org/callsite/1.0.0
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/has-cors/1.0.3
npm http GET https://registry.npmjs.org/parsejson/0.0.1
npm http GET https://registry.npmjs.org/parseqs/0.0.2
npm http GET https://registry.npmjs.org/parseuri/0.0.4
npm http GET https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm http GET https://registry.npmjs.org/component-inherit/0.0.3
npm http GET https://registry.npmjs.org/debug/1.0.4
npm http 304 https://registry.npmjs.org/has-cors/1.0.3
npm http 304 https://registry.npmjs.org/parsejson/0.0.1
npm http 304 https://registry.npmjs.org/parseqs/0.0.2
npm http 304 https://registry.npmjs.org/debug/1.0.4
npm http 304 https://registry.npmjs.org/component-inherit/0.0.3

> utf-8-validate@1.1.0 install /usr/local/lib/node_modules/maildev/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/parseuri/0.0.4

> bufferutil@1.1.0 install /usr/local/lib/node_modules/maildev/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/maildev/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm http 200 https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/maildev/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing bufferutil@1.1.0
npm http GET https://github.com/component/global/archive/v2.0.1.tar.gz

> utf-8-validate@1.1.0 install /usr/local/lib/node_modules/maildev/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild


> bufferutil@1.1.0 install /usr/local/lib/node_modules/maildev/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

npm http 200 https://github.com/component/global/archive/v2.0.1.tar.gz
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/maildev/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing utf-8-validate@1.1.0
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:431:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-30-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/maildev/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing bufferutil@1.1.0
/usr/local/bin/maildev -> /usr/local/lib/node_modules/maildev/bin/maildev
maildev@0.11.0 /usr/local/lib/node_modules/maildev
├── open@0.0.5
├── smtp-connection@1.3.1
├── smtp-server@1.4.2
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── simplesmtp@0.3.35 (xoauth2@0.1.8, rai@0.1.12)
├── mailparser@0.5.2 (mime@1.3.4, mimelib@0.2.19, uue@2.1.1, encoding@0.1.11)
├── express@4.13.1 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.0, cookie@0.1.3, path-to-regexp@0.1.6, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, vary@1.0.1, etag@1.7.0, content-type@1.0.1, parseurl@1.3.0, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, finalhandler@0.4.0, qs@4.0.0, debug@2.2.0, on-finished@2.3.0, proxy-addr@1.0.8, send@0.13.0, type-is@1.6.5, accepts@1.2.11)
├── mailcomposer@0.2.12 (mime@1.2.11, he@0.3.6, dkim-signer@0.1.2, follow-redirects@0.0.3, mimelib@0.2.19)
└── socket.io@1.3.6 (debug@2.1.0, has-binary-data@0.1.3, socket.io-adapter@0.3.1, socket.io-parser@2.2.4, engine.io@1.5.2, socket.io-client@1.3.6)
```

Do you have any idea ?

**Comment by djfarrelly** [comment]
Hey @babeuloula, I've been out of town, hoping to look into this one night this week, any success since you added this issue?

**Comment by babeuloula** [comment]
Hello @djfarrelly, sorry I was also on vacation and I have not retried.

**Comment by djfarrelly** [comment]
Hey @babeuloula, I'm not quite sure what seems to be happening from the logs here. The `/bin/sh: 1: node: not found` makes me think it could be an issue with that version of Node/npm. I see you're on `{"node":"v0.10.25","npm":"1.3.10"}` - Maybe try updating npm to 2.x and maybe even Node to the latest 0.10.x?

**Comment by jameshhx** [comment]
Long shot..but try creating a symlink to the nodejs command named node. If nodejs has been installed via the default package available in Aptitude, it installs the binary as nodejs, not node, due to another package using the binary name node.

**Comment by babeuloula** [comment]
Hello, 

I tried to install nodeJS with this link now : https://github.com/joyent/node/wiki/installing-node.js-via-package-manager
And maildev works.

Thanks.
