### ISSUE TITLE
postfix denies relayed mails

### ISSUE THREAD

**Issue by diresi** [djfarrelly/MailDev#86]
I'm using the docker image of v0.12.0.

I'm inserting simple mails using the unix `mail` command:
``` bash
echo "teest" | mail -S 'smtp=smtp://localhost:1025' -s 'a subject' recipient@example.com
```

My outgoing configuration seems OK, but when I try to relay the above email postfix responds with
```
NOQUEUE: reject: RCPT from unknown[192.168.88.105]: 550 5.1.1 <null>: Recipient address rejected: User unknown in local recipient table; from=<> to=<null> proto=ESMTP helo=<[127.0.0.1]>
```

This appearently means that both `From:` and `To:` are empty.
I "fixed" this using a small patch, but I have no clue whether this is the correct approach ...

The patch is:
``` patch
diff --git a/lib/mailserver.js b/lib/mailserver.js
index 02d7211..b617e5a 100644
--- a/lib/mailserver.js
+++ b/lib/mailserver.js
@@ -255,7 +255,16 @@ function relayMail(idOrMailObject, autoRelay, done) {
 
       var mailSendCallback = function(err, info) {
 
-        var recipients = mail.envelope.to.map(function(toItem) { return toItem.address; });
+        var get_address = function(address) {
+          email = address.address;
+          if (email === undefined) {
+            email = address;
+          }
+          return email;
+        }
+
+        var recipients = mail.envelope.to.map(get_address);
+        var sender = get_address(mail.envelope.from);
 
         if (autoRelay && mailServer.autoRelayRules) {
           recipients = getAutoRelayableRecipients(recipients);
@@ -267,7 +276,7 @@ function relayMail(idOrMailObject, autoRelay, done) {
         }
 
         mailServer.client.send({
-          from: mail.envelope.from.address,
+          from: sender,
           to: recipients
         }, rawEmailStream, function (err, info) {
           if (err) {
```

I'd be happy to create a merge request if you're willing to accept this patch.

**Comment by diresi** [comment]
Hmm. Although relaying works (the mail is delivered) MailDev exits several minutes later. The full output is:
```
Temporary directory created at /tmp/maildev
Temporary directory created at /tmp/maildev/1
MailDev outgoing SMTP Server ${SMTP_SERVER}:25 (user:undefined, pass:undefined, secure:no)
MailDev app running at 0.0.0.0:80
MailDev SMTP Server running at 0.0.0.0:25



events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Unexpected Response
    at SMTPConnection._processResponse (/app/node_modules/smtp-connection/src/smtp-connection.js:514:30)
    at SMTPConnection._onData (/app/node_modules/smtp-connection/src/smtp-connection.js:357:10)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

**Comment by Ndrou** [comment]
I think I had the same error, do you try to relay several emails at the same time?

I think there's a problem on the sending email's workflow. I added a queue to this pull request #85 to avoid SMTP crashes.

**Comment by diresi** [comment]
@Ndrou No, It was only one mail.

**Comment by donut87** [comment]
<poll> Same error here.

**Comment by donut87** [comment]
The problem seems to be a timeout. We don't receive any SMTP-Close on our SMTP-Server and the server sends a timeout after 5 minutes.
