### ISSUE TITLE
SMTP-Connection can't handle simlpe greeting

### ISSUE THREAD

**Issue by donut87** [djfarrelly/MailDev#88]
When the server sends a 250, which is an exceptionally good response, the whole application crashes.

Error: Invalid greeting from server:
250 2.0.0 Ok: queued as B4C8112124D
    at SMTPConnection._actionGreeting (/usr/lib/node_modules/maildev/node_modules/smtp-connection/src/smtp-connection.js:611:23)
    at SMTPConnection._processResponse (/usr/lib/node_modules/maildev/node_modules/smtp-connection/src/smtp-connection.js:511:16)
    at SMTPConnection._onData (/usr/lib/node_modules/maildev/node_modules/smtp-connection/src/smtp-connection.js:357:10)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
    at process._tickCallback (node.js:442:13)

**Comment by djfarrelly** [comment]
Hey @donut87! I wonder if this is an issue with [smtp-connection](https://github.com/andris9/smtp-connection) and not MailDev itself - is this still happening for you?

**Comment by donut87** [comment]
It is still happening. Yes it is the underlying smtp-connection. So actually this bug should be closed here and reopened there.
